2020-07-17 11:00:31,868 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-17 11:00:32,998 :INFO : test_e2e :Entered Password Successfully
2020-07-17 11:00:43,512 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-17 11:00:47,669 :INFO : test_contact :Create Contact Page
2020-07-17 11:00:48,933 :INFO : test_contact :Enter Name as 'Test' 
2020-07-17 11:00:50,430 :INFO : test_contact :Entered lastname as 'User' 
2020-07-17 11:00:51,554 :INFO : test_contact :Entered mobile number as '9898989898' 
2020-07-17 11:00:56,574 :ERROR : test_contact :('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1045, in _send_output
    self.send(chunk)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 967, in send
    self.sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 59, in test_contact
    State = contactPage.getContactState()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\ContactPage.py", line 39, in getContactState
    return self.driver.find_element(*ContactPage.contactState)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1045, in _send_output
    self.send(chunk)
  File "C:\Users\raa918070\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 967, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
2020-07-17 11:02:52,125 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-17 11:02:53,254 :INFO : test_e2e :Entered Password Successfully
2020-07-17 11:03:04,048 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-17 11:03:08,251 :INFO : test_contact :Create Contact Page
2020-07-17 11:03:09,563 :INFO : test_contact :Enter Name as 'Test' 
2020-07-17 11:03:10,689 :INFO : test_contact :Entered lastname as 'User' 
2020-07-17 11:03:12,165 :INFO : test_contact :Entered mobile number as '9898989898' 
2020-07-17 11:03:19,189 :INFO : test_contact :Selected State as 'Maharashtra' 
2020-07-17 11:03:20,331 :INFO : test_contact :Selected Taluka as 'Arvi' 
2020-07-17 11:03:43,535 :INFO : test_contact :Entered address line1 as 'Add1' 
2020-07-17 11:03:44,664 :INFO : test_contact :Entered address line2 as 'Add2' 
2020-07-17 11:04:25,211 :INFO : test_contact :Success Message- Contact created successfully
2020-07-17 11:04:25,212 :INFO : test_contact :Contact Id- 1-C3SGNLN
2020-07-17 11:04:27,512 :INFO : test_Opportuinity :Clicked on Opportunity radio button
2020-07-17 11:04:28,069 :INFO : test_Opportuinity :Moved on Create Opportunity page
2020-07-17 11:04:30,783 :INFO : test_Opportuinity :Entered VC number '28182024ABFR' 
2020-07-17 11:04:34,291 :INFO : test_Opportuinity :Selected Vehicle application as 'Fruits & Vegetables' 
2020-07-17 11:04:34,984 :INFO : test_Opportuinity :Selected Body type as 'High Deck' 
2020-07-17 11:04:37,155 :INFO : test_Opportuinity :Selected Customer type as 'Government Existing' 
2020-07-17 11:04:39,359 :INFO : test_Opportuinity :Selected Source of contact as 'Customer Meet' 
2020-07-17 11:04:40,056 :INFO : test_Opportuinity :Selected quantity as '2' 
2020-07-17 11:04:42,587 :INFO : test_Opportuinity :Selected Likely Purchase month as 'August' 
2020-07-17 11:04:44,699 :INFO : test_Opportuinity :Selected Usage Category as 'Captive' 
2020-07-17 11:04:49,534 :INFO : test_Opportuinity :Entered MMGeo location as 'Akola' 
2020-07-17 11:04:51,520 :INFO : test_Opportuinity :Entered '8999413547' mobile number to create opportunity for this contact
2020-07-17 11:05:42,707 :INFO : test_Opportuinity :Entered all opty details and clicked on Submit button 
2020-07-17 11:05:42,799 :ERROR : test_Opportuinity :Opportunity is not created successfully due to error : Cannot find entry 'Government Existing' in the bounded picklist for the field 'TMCV Customer Type' in integration component 'Opportunity'(SBL-EAI-04401)

2020-07-17 11:47:31,396 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-17 11:47:32,850 :INFO : test_e2e :Entered Password Successfully
2020-07-17 11:47:43,442 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-17 11:47:47,611 :INFO : test_contact :Create Contact Page
2020-07-17 11:47:48,896 :INFO : test_contact :Enter Name as 'Test' 
2020-07-17 11:47:50,017 :INFO : test_contact :Entered lastname as 'User' 
2020-07-17 11:47:51,358 :INFO : test_contact :Entered mobile number as '9898989898' 
2020-07-17 11:47:58,341 :INFO : test_contact :Selected State as 'Maharashtra' 
2020-07-17 11:47:59,479 :INFO : test_contact :Selected Taluka as 'Arvi' 
2020-07-17 11:48:22,662 :INFO : test_contact :Entered address line1 as 'Add1' 
2020-07-17 11:48:23,787 :INFO : test_contact :Entered address line2 as 'Add2' 
2020-07-17 11:49:04,694 :INFO : test_contact :Success Message- Contact created successfully
2020-07-17 11:49:04,694 :INFO : test_contact :Contact Id- 1-C3SGNN1
2020-07-17 11:49:07,199 :INFO : test_Opportuinity :Clicked on Opportunity radio button
2020-07-17 11:49:07,769 :INFO : test_Opportuinity :Moved on Create Opportunity page
2020-07-17 11:49:10,485 :INFO : test_Opportuinity :Entered VC number '28182024ABFR' 
2020-07-17 11:49:14,023 :INFO : test_Opportuinity :Selected Vehicle application as 'Fruits & Vegetables' 
2020-07-17 11:49:14,719 :INFO : test_Opportuinity :Selected Body type as 'High Deck' 
2020-07-17 11:49:16,922 :INFO : test_Opportuinity :Selected Customer type as 'Government Existing' 
2020-07-17 11:49:19,210 :INFO : test_Opportuinity :Selected Source of contact as 'Customer Meet' 
2020-07-17 11:49:19,916 :INFO : test_Opportuinity :Selected quantity as '2' 
2020-07-17 11:49:22,440 :INFO : test_Opportuinity :Selected Likely Purchase month as 'August' 
2020-07-17 11:49:24,501 :INFO : test_Opportuinity :Selected Usage Category as 'Captive' 
2020-07-17 11:49:29,335 :INFO : test_Opportuinity :Entered MMGeo location as 'Akola' 
2020-07-17 11:49:31,239 :INFO : test_Opportuinity :Entered '8999413547' mobile number to create opportunity for this contact
2020-07-17 11:50:22,403 :INFO : test_Opportuinity :Entered all opty details and clicked on Submit button 
2020-07-17 11:50:22,478 :ERROR : test_Opportuinity :Opportunity is not created successfully due to error : Cannot find entry 'Government Existing' in the bounded picklist for the field 'TMCV Customer Type' in integration component 'Opportunity'(SBL-EAI-04401)
2020-07-18 16:27:43,642 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-18 16:27:45,778 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-18 18:03:25,148 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-18 18:03:27,268 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-20 10:29:43,833 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-20 10:29:45,952 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 48, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-20 10:40:53,973 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-20 10:40:56,088 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 10:47:31,252 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 10:47:33,416 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:22:50,892 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:22:52,967 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "c:\users\raa918070\appdata\local\programs\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "c:\users\raa918070\appdata\local\programs\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\appdata\local\programs\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:30:41,882 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:30:43,985 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:37:55,795 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:39:15,973 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:50:31,179 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:50:33,276 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:52:28,344 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 13:52:30,442 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:01:57,088 :ERROR : test_login :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:01:59,206 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:04:44,730 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:04:46,843 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:14:59,640 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:15:01,735 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:16:46,887 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:16:48,989 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:23:19,541 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:23:21,646 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:26:58,437 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:27:00,556 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 47, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:58:13,087 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 14:58:15,205 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:09:42,951 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:09:45,055 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:20:05,819 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:20:07,905 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:21:41,207 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:21:43,310 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:24:52,514 :ERROR : test_e2e :Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:24:54,632 :ERROR : test_contact :Message: Locator Strategy 'css selector' is not supported for this session
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

2020-07-21 15:32:58,412 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-21 15:32:59,531 :INFO : test_e2e :Entered Password Successfully
2020-07-21 15:34:22,274 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-21 15:34:23,418 :INFO : test_e2e :Entered Password Successfully
2020-07-21 15:34:33,993 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-21 15:34:38,156 :INFO : test_contact :Create Contact Page
2020-07-21 15:34:42,842 :INFO : test_contact :Enter Name as 'Test' 
2020-07-21 15:34:43,973 :INFO : test_contact :Entered lastname as 'User' 
2020-07-21 15:34:45,095 :INFO : test_contact :Entered mobile number as '9898989898' 
2020-07-21 15:34:52,084 :INFO : test_contact :Selected State as 'Maharashtra' 
2020-07-21 15:34:53,230 :INFO : test_contact :Selected Taluka as 'Arvi' 
2020-07-21 15:35:17,024 :INFO : test_contact :Entered address line1 as 'Add1' 
2020-07-21 15:35:18,138 :INFO : test_contact :Entered address line2 as 'Add2' 
2020-07-21 15:35:58,383 :INFO : test_contact :Success Message- Contact created successfully
2020-07-21 15:35:58,383 :INFO : test_contact :Contact Id- 1-C3UDWOH
2020-07-21 15:36:00,556 :INFO : test_opportuinity :Clicked on Opportunity radio button
2020-07-21 15:36:01,118 :INFO : test_opportuinity :Moved on Create Opportunity page
2020-07-21 15:36:04,164 :INFO : test_opportuinity :Entered VC number '28182024ABFR' 
2020-07-21 15:36:07,725 :INFO : test_opportuinity :Selected Vehicle application as 'Fruits & Vegetables' 
2020-07-21 15:36:08,432 :INFO : test_opportuinity :Selected Body type as 'High Deck' 
2020-07-21 15:36:10,601 :INFO : test_opportuinity :Selected Customer type as 'Government Existing' 
2020-07-21 15:36:12,849 :INFO : test_opportuinity :Selected Source of contact as 'Customer Meet' 
2020-07-21 15:36:13,554 :INFO : test_opportuinity :Selected quantity as '2' 
2020-07-21 15:36:16,095 :INFO : test_opportuinity :Selected Likely Purchase month as 'August' 
2020-07-21 15:36:18,148 :INFO : test_opportuinity :Selected Usage Category as 'Captive' 
2020-07-21 15:36:23,031 :INFO : test_opportuinity :Entered MMGeo location as 'Akola' 
2020-07-21 15:36:25,024 :INFO : test_opportuinity :Entered '8999413547' mobile number to create opportunity for this contact
2020-07-21 15:37:16,170 :INFO : test_opportuinity :Entered all opty details and clicked on Submit button 
2020-07-21 15:37:16,254 :ERROR : test_opportuinity :Opportunity is not created successfully due to error : Creating Opportunity
2020-07-30 12:42:46,980 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-30 15:55:27,095 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 09:47:23,149 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 49, in test_contact
    contactPage.getContactButton().click()
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 27, in getContactButton
    return self.driver.find_element(*ContactPage.contactButton)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 09:50:09,047 :ERROR : test_e2e :Message: An element could not be located on the page using the given search parameters.

2020-07-31 10:01:52,613 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 10:01:53,771 :INFO : test_e2e :Entered Password Successfully
2020-07-31 10:02:04,383 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 10:02:27,932 :INFO : test_contact :Create Contact Page
2020-07-31 10:03:18,347 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 10:05:32,733 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 10:05:33,887 :INFO : test_e2e :Entered Password Successfully
2020-07-31 10:05:45,016 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 10:05:51,788 :INFO : test_contact :Create Contact Page
2020-07-31 10:06:42,190 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 10:11:26,703 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 10:11:27,841 :INFO : test_e2e :Entered Password Successfully
2020-07-31 10:11:39,650 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 10:11:44,987 :INFO : test_contact :Create Contact Page
2020-07-31 10:12:35,343 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 10:13:02,856 :INFO : test_opportuinity :Clicked on Opportunity radio button
2020-07-31 10:13:03,408 :INFO : test_opportuinity :Moved on Create Opportunity page
2020-07-31 10:13:05,980 :INFO : test_opportuinity :Entered VC number '28182024ABFR' 
2020-07-31 10:28:08,808 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 10:28:09,941 :INFO : test_e2e :Entered Password Successfully
2020-07-31 10:28:21,502 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 10:28:25,615 :INFO : test_contact :Create Contact Page
2020-07-31 10:29:17,281 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 10:30:00,957 :INFO : test_opportuinity :Clicked on Opportunity radio button
2020-07-31 10:30:01,590 :INFO : test_opportuinity :Moved on Create Opportunity page
2020-07-31 10:30:04,310 :INFO : test_opportuinity :Entered VC number '28182024ABFR' 
2020-07-31 10:33:04,950 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 10:33:06,079 :INFO : test_e2e :Entered Password Successfully
2020-07-31 10:33:23,015 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 10:33:27,126 :INFO : test_contact :Create Contact Page
2020-07-31 10:34:17,507 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\raa918070\pycharmprojects\eguru_sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 10:35:06,003 :INFO : test_opportuinity :Clicked on Opportunity radio button
2020-07-31 10:35:06,890 :INFO : test_opportuinity :Moved on Create Opportunity page
2020-07-31 10:35:09,623 :INFO : test_opportuinity :Entered VC number '28182024ABFR' 
2020-07-31 16:21:50,129 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 16:21:51,261 :INFO : test_e2e :Entered Password Successfully
2020-07-31 16:22:02,648 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 16:22:32,475 :INFO : test_contact :Create Contact Page
2020-07-31 16:28:19,432 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 16:28:20,567 :INFO : test_e2e :Entered Password Successfully
2020-07-31 16:28:31,664 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 16:28:35,778 :INFO : test_contact :Create Contact Page
2020-07-31 16:29:26,003 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

2020-07-31 16:32:11,492 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 16:32:12,629 :INFO : test_e2e :Entered Password Successfully
2020-07-31 16:32:23,184 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 16:32:27,319 :INFO : test_contact :Create Contact Page
2020-07-31 16:32:35,470 :ERROR : test_contact :Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

2020-07-31 16:55:48,791 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 16:55:49,923 :INFO : test_e2e :Entered Password Successfully
2020-07-31 16:56:00,355 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 16:56:04,484 :INFO : test_contact :Create Contact Page
2020-07-31 16:56:05,782 :INFO : test_contact :Entered Name as 'Test' 
2020-07-31 16:56:06,908 :INFO : test_contact :Entered lastname as 'User' 
2020-07-31 16:56:08,037 :INFO : test_contact :Entered mobile number as '9898989898' 
2020-07-31 16:56:15,022 :INFO : test_contact :Selected State as 'Maharashtra' 
2020-07-31 16:56:16,169 :INFO : test_contact :Selected Taluka as 'Arvi' 
2020-07-31 16:56:39,363 :INFO : test_contact :Entered address line1 as 'Add1' 
2020-07-31 16:56:40,494 :INFO : test_contact :Entered address line2 as 'Add2' 
2020-07-31 16:57:20,731 :INFO : test_contact :Success Message- Contact created successfully
2020-07-31 16:57:20,732 :INFO : test_contact :Contact Id- 1-C3Z91RT
2020-07-31 16:57:23,674 :INFO : test_opportuinity :Clicked on Opportunity radio button
2020-07-31 16:57:24,243 :INFO : test_opportuinity :Moved on Create Opportunity page
2020-07-31 16:57:26,993 :INFO : test_opportuinity :Entered VC number '28182024ABFR' 
2020-07-31 16:57:30,552 :INFO : test_opportuinity :Selected Vehicle application as 'Fruits & Vegetables' 
2020-07-31 16:57:31,260 :INFO : test_opportuinity :Selected Body type as 'High Deck' 
2020-07-31 16:57:33,422 :INFO : test_opportuinity :Selected Customer type as 'Government Existing' 
2020-07-31 16:57:35,649 :INFO : test_opportuinity :Selected Source of contact as 'Customer Meet' 
2020-07-31 16:57:36,341 :INFO : test_opportuinity :Selected quantity as '2' 
2020-07-31 16:57:38,893 :INFO : test_opportuinity :Selected Likely Purchase month as 'August' 
2020-07-31 16:57:40,966 :INFO : test_opportuinity :Selected Usage Category as 'Captive' 
2020-07-31 16:57:45,766 :INFO : test_opportuinity :Entered MMGeo location as 'Akola' 
2020-07-31 16:57:47,681 :INFO : test_opportuinity :Entered '8999413547' mobile number to create opportunity for this contact
2020-07-31 16:58:38,796 :INFO : test_opportuinity :Entered all opty details and clicked on Submit button 
2020-07-31 16:58:38,851 :ERROR : test_opportuinity :Opportunity is not created successfully due to error : Cannot find entry 'Government Existing' in the bounded picklist for the field 'TMCV Customer Type' in integration component 'Opportunity'(SBL-EAI-04401)
2020-07-31 17:00:25,376 :INFO : test_e2e :Entered UserName 'DUSER146' Successfully
2020-07-31 17:00:26,509 :INFO : test_e2e :Entered Password Successfully
2020-07-31 17:00:36,845 :INFO : test_e2e :Login Successfully by using DSM credentials
2020-07-31 17:00:40,976 :INFO : test_contact :Create Contact Page
2020-07-31 17:00:42,250 :INFO : test_contact :Entered Name as 'Test' 
2020-07-31 17:00:43,383 :INFO : test_contact :Entered lastname as 'User' 
2020-07-31 17:00:44,516 :INFO : test_contact :Entered mobile number as '9898989898' 
2020-07-31 17:00:51,527 :INFO : test_contact :Selected State as 'Maharashtra' 
2020-07-31 17:00:52,667 :INFO : test_contact :Selected Taluka as 'Arvi' 
2020-07-31 17:01:15,862 :INFO : test_contact :Entered address line1 as 'Add1' 
2020-07-31 17:01:16,984 :INFO : test_contact :Entered address line2 as 'Add2' 
2020-07-31 17:01:57,250 :INFO : test_contact :Success Message- Contact created successfully
2020-07-31 17:01:57,250 :INFO : test_contact :Contact Id- 1-C3Z96X3
2020-07-31 17:01:59,718 :INFO : test_opportuinity :Clicked on Opportunity radio button
2020-07-31 17:02:00,286 :INFO : test_opportuinity :Moved on Create Opportunity page
2020-07-31 17:02:03,069 :INFO : test_opportuinity :Entered VC number '28182024ABFR' 
2020-07-31 17:02:07,009 :INFO : test_opportuinity :Selected Vehicle application as 'Fruits & Vegetables' 
2020-07-31 17:02:07,711 :INFO : test_opportuinity :Selected Body type as 'High Deck' 
2020-07-31 17:02:09,906 :INFO : test_opportuinity :Selected Customer type as 'Government Existing' 
2020-07-31 17:02:12,160 :INFO : test_opportuinity :Selected Source of contact as 'Customer Meet' 
2020-07-31 17:02:12,884 :INFO : test_opportuinity :Selected quantity as '2' 
2020-07-31 17:02:15,485 :INFO : test_opportuinity :Selected Likely Purchase month as 'August' 
2020-07-31 17:02:17,619 :INFO : test_opportuinity :Selected Usage Category as 'Captive' 
2020-07-31 17:02:22,124 :INFO : test_opportuinity :Entered MMGeo location as 'Akola' 
2020-07-31 17:02:24,062 :INFO : test_opportuinity :Entered '8999413547' mobile number to create opportunity for this contact
2020-07-31 17:03:15,185 :INFO : test_opportuinity :Entered all opty details and clicked on Submit button 
2020-07-31 17:03:15,255 :ERROR : test_opportuinity :Opportunity is not created successfully due to error : Cannot find entry 'Government Existing' in the bounded picklist for the field 'TMCV Customer Type' in integration component 'Opportunity'(SBL-EAI-04401)
2020-08-01 01:17:47,433 :ERROR : test_e2e :Message: An element could not be located on the page using the given search parameters.

2020-08-01 01:17:54,078 :INFO : test_contact :Create Contact Page
2020-08-01 01:18:44,417 :ERROR : test_contact :Message: An element could not be located on the page using the given search parameters.
Traceback (most recent call last):
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\tests\test_e2e.py", line 52, in test_contact
    contactPage.getContactName ().send_keys ("Test")
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\pageObjects\ContactPage.py", line 30, in getContactName
    return self.driver.find_element(*ContactPage.contactName)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\raa918070\PycharmProjects\Eguru_Sandbox\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

